# Generated by Django 4.2.4 on 2023-08-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the Meal')),
                ('recipe', models.TextField(verbose_name='Recipe of the Meal')),
                ('image', models.ImageField(upload_to='images')),
                ('published', models.BooleanField(default=True)),
            ],
        ),
    ]
